DATE_FORMAT = '%Y-%m-%d'

SPECIAL_KEYS = {
    # Common character keys
    'space': ' ',
    'enter': '\n',
    'tab': '\t',
    'backspace': '\n[BACKSPACE]',
    'esc': '\n[ESCAPE]',
    'delete': '\n[DELETE]',
    'home': '\n[HOME]',
    'end': '\n[END]',
    'page up': '\n[PAGE UP]',
    'page down': '\n[PAGE DOWN]',
    'insert': '\n[INSERT]',
    'up': '\n[UP ARROW]',
    'down': '\n[DOWN ARROW]',
    'left': '\n[LEFT ARROW]',
    'right': '\n[RIGHT ARROW]',
    # Modifier keys
    'shift': '\n[SHIFT]',
    'shift left': '\n[LEFT SHIFT]',
    'shift right': '\n[RIGHT SHIFT]',
    'ctrl': '\n[CTRL]',
    'ctrl left': 'v[LEFT CTRL]',
    'ctrl right': '\n[RIGHT CTRL]',
    'alt': '\n[ALT]',
    'alt left': '\n[LEFT ALT]',
    'alt right': '\n[RIGHT ALT]',
    'caps lock': '\n[CAPS LOCK]',
    'num lock': '\n[NUM LOCK]',
    'scroll lock': '\n[SCROLL LOCK]',
    # Function keys
    'f1': '\n[F1]',
    'f2': '\n[F2]',
    'f3': '\n[F3]',
    'f4': '\n[F4]',
    'f5': '\n[F5]',
    'f6': '\n[F6]',
    'f7': '\n[F7]',
    'f8': '\n[F8]',
    'f9': '\n[F9]',
    'f10': '\n[F10]',
    'f11': '\n[F11]',
    'f12': '\n[F12]',
    # Numpad keys
    'num 0': '0',
    'num 1': '1',
    'num 2': '2',
    'num 3': '3',
    'num 4': '4',
    'num 5': '5',
    'num 6': '6',
    'num 7': '7',
    'num 8': '8',
    'num 9': '9',
    'num +': '+',
    'num -': '-',
    'num *': '*',
    'num /': '/',
    'num .': '.',
    'num enter': '\n',
    # Special keys
    'print screen': '\n[PRINT SCREEN]',
    'pause': '\n[PAUSE]',
    'menu': '\n[MENU]',
    # Miscellaneous keys
    'play/pause media': '\n[PLAY/PAUSE MEDIA]',
    'stop media': '\n[STOP MEDIA]',
    'previous track': '\n[PREVIOUS TRACK]',
    'next track': '\n[NEXT TRACK]',
    'volume mute': '\n[VOLUME MUTE]',
    'volume down': '\n[VOLUME DOWN]',
    'volume up': '\n[VOLUME UP]',
    'browser home': '\n[BROWSER HOME]',
    'browser search': '\n[BROWSER SEARCH]',
    'browser favorites': '\n[BROWSER FAVORITES]',
    'browser refresh': '\n[BROWSER REFRESH]',
    'browser stop': '\n[BROWSER STOP]',
    'browser forward': '\n[BROWSER FORWARD]',
    'browser back': '\n[BROWSER BACK]',
    # Unknown keys
    'unknown': '\n[UNKNOWN]'
}
