DATE_FORMAT = '%Y-%m-%d'

KEY_MAPPING = {
    # Common character keys
    'space': ' ',
    'enter': '\n',
    'tab': '\t',
    'backspace': '\n[BACKSPACE]\n',
    'esc': '\n[ESCAPE]\n',
    'delete': '\n[DELETE]\n',
    'home': '\n[HOME]\n',
    'end': '\n[END]\n',
    'page up': '\n[PAGE UP]\n',
    'page down': '\n[PAGE DOWN]\n',
    'insert': '\n[INSERT]\n',
    'up': '\n[UP ARROW]\n',
    'down': '\n[DOWN ARROW]\n',
    'left': '\n[LEFT ARROW]\n',
    'right': '\n[RIGHT ARROW]\n',
    # Modifier keys
    'shift': '\n[SHIFT]\n',
    'shift left': '\n[LEFT SHIFT]\n',
    'shift right': '\n[RIGHT SHIFT]\n',
    'ctrl': '\n[CTRL]\n',
    'ctrl left': 'v[LEFT CTRL]\n',
    'ctrl right': '\n[RIGHT CTRL]\n',
    'alt': '\n[ALT]\n',
    'alt left': '\n[LEFT ALT]\n',
    'alt right': '\n[RIGHT ALT]\n',
    'caps lock': '\n[CAPS LOCK]\n',
    'num lock': '\n[NUM LOCK]\n',
    'scroll lock': '\n[SCROLL LOCK]\n',
    # Function keys
    'f1': '\n[F1]\n',
    'f2': '\n[F2]\n',
    'f3': '\n[F3]\n',
    'f4': '\n[F4]\n',
    'f5': '\n[F5]\n',
    'f6': '\n[F6]\n',
    'f7': '\n[F7]\n',
    'f8': '\n[F8]\n',
    'f9': '\n[F9]\n',
    'f10': '\n[F10]\n',
    'f11': '\n[F11]\n',
    'f12': '\n[F12]\n',
    # Numpad keys
    'num 0': '0',
    'num 1': '1',
    'num 2': '2',
    'num 3': '3',
    'num 4': '4',
    'num 5': '5',
    'num 6': '6',
    'num 7': '7',
    'num 8': '8',
    'num 9': '9',
    'num +': '+',
    'num -': '-',
    'num *': '*',
    'num /': '/',
    'num .': '.',
    'num enter': '\n',
    # Special keys
    'print screen': '\n[PRINT SCREEN]\n',
    'pause': '\n[PAUSE]\n',
    'menu': '\n[MENU]\n',
    # Miscellaneous keys
    'play/pause media': '\n[PLAY/PAUSE MEDIA]\n',
    'stop media': '\n[STOP MEDIA]\n',
    'previous track': '\n[PREVIOUS TRACK]\n',
    'next track': '\n[NEXT TRACK]\n',
    'volume mute': '\n[VOLUME MUTE]\n',
    'volume down': '\n[VOLUME DOWN]\n',
    'volume up': '\n[VOLUME UP]\n',
    'browser home': '\n[BROWSER HOME]\n',
    'browser search': '\n[BROWSER SEARCH]\n',
    'browser favorites': '\n[BROWSER FAVORITES]\n',
    'browser refresh': '\n[BROWSER REFRESH]\n',
    'browser stop': '\n[BROWSER STOP]\n',
    'browser forward': '\n[BROWSER FORWARD]\n',
    'browser back': '\n[BROWSER BACK]\n',
    # Unknown keys
    'unknown': '\n[UNKNOWN]\n'
}
